// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCard: typeof import('@nutui/nutui-taro')['Card']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
